// Auto-loads any src/assets/products/<id>.jpg generated by the AI image script.
// Products without a generated image fall back to the emoji in the card.
const modules = import.meta.glob("@/assets/products/*.jpg", {
  eager: true,
  query: "?url",
  import: "default",
}) as Record<string, string>;

export const productImages: Record<string, string> = Object.fromEntries(
  Object.entries(modules).map(([path, url]) => {
    const id = path.split("/").pop()!.replace(/\.jpg$/, "");
    return [id, url];
  })
);
