export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  size: string;
  rating: number;
  badge?: string;
  emoji: string;
};

export const categories = [
  "All",
  "Whisky",
  "Vodka",
  "Gin",
  "Wine",
  "Tequila",
  "Champagne",
  "Beer",
  "Kenyan",
  "Cognac",
  "Cider",
  "Rum",
  "Liqueur",
] as const;

export const products: Product[] = [
  {
    id: "WH-IMG-0001-JWB",
    name: "Johnnie Walker Black Label",
    category: "Whisky",
    price: 4500,
    oldPrice: 5200,
    size: "750ml",
    rating: 4.8,
    badge: "Bestseller",
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0004-JWDB",
    name: "Johnnie Walker Double Black",
    category: "Whisky",
    price: 6200,
    size: "750ml",
    rating: 4.9,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0009-GF12",
    name: "Glenfiddich 12 Years",
    category: "Whisky",
    price: 7800,
    size: "750ml",
    rating: 4.9,
    badge: "Premium",
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0005-JMS",
    name: "Jameson Irish Whiskey",
    category: "Whisky",
    price: 3200,
    oldPrice: 3600,
    size: "750ml",
    rating: 4.7,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0012-SNG12",
    name: "The Singleton 12",
    category: "Whisky",
    price: 6500,
    size: "700ml",
    rating: 4.8,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0006-JD7",
    name: "Jack Daniel's Old No.7",
    category: "Whisky",
    price: 4200,
    size: "750ml",
    rating: 4.8,
    badge: "Hot",
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0007-CR12",
    name: "Chivas Regal 12",
    category: "Whisky",
    price: 5500,
    size: "750ml",
    rating: 4.7,
    emoji: "🥃",
  },
  {
    id: "w8",
    name: "Glenlivet Founder's Reserve",
    category: "Whisky",
    price: 6800,
    size: "700ml",
    rating: 4.8,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0014-BLF",
    name: "Ballantine's Finest",
    category: "Whisky",
    price: 2900,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0015-BNW",
    name: "Black & White Scotch",
    category: "Whisky",
    price: 2400,
    size: "750ml",
    rating: 4.4,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0017-MCL12",
    name: "The Macallan 12 Years",
    category: "Whisky",
    price: 15500,
    size: "700ml",
    rating: 4.9,
    badge: "Luxury",
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0008-CR18",
    name: "Chivas Regal 18",
    category: "Whisky",
    price: 11500,
    size: "750ml",
    rating: 4.8,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0021-SMR",
    name: "Smirnoff Red Label",
    category: "Vodka",
    price: 1800,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "v2",
    name: "Cîroc Ultra Premium",
    category: "Vodka",
    price: 7200,
    size: "750ml",
    rating: 4.9,
    badge: "Luxury",
    emoji: "🍸",
  },
  {
    id: "v3",
    name: "Absolut Blue",
    category: "Vodka",
    price: 2800,
    oldPrice: 3200,
    size: "750ml",
    rating: 4.6,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0028-CHV",
    name: "Chrome Vodka",
    category: "Vodka",
    price: 1200,
    size: "750ml",
    rating: 4.2,
    emoji: "🍸",
  },
  {
    id: "v5",
    name: "Belvedere Pure",
    category: "Vodka",
    price: 6500,
    size: "750ml",
    rating: 4.8,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0026-GRG",
    name: "Grey Goose",
    category: "Vodka",
    price: 6800,
    size: "750ml",
    rating: 4.9,
    badge: "Premium",
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0030-KTO",
    name: "Ketel One",
    category: "Vodka",
    price: 3500,
    size: "750ml",
    rating: 4.7,
    emoji: "🍸",
  },
  {
    id: "g1",
    name: "Gordon's London Dry",
    category: "Gin",
    price: 2200,
    size: "750ml",
    rating: 4.6,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0032-BSP",
    name: "Bombay Sapphire",
    category: "Gin",
    price: 3800,
    oldPrice: 4200,
    size: "750ml",
    rating: 4.8,
    badge: "Hot",
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0035-GLB",
    name: "Gilbey's Gin",
    category: "Gin",
    price: 1700,
    size: "750ml",
    rating: 4.4,
    emoji: "🍸",
  },
  {
    id: "g4",
    name: "Beefeater London Dry",
    category: "Gin",
    price: 3200,
    size: "750ml",
    rating: 4.6,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0033-TQY",
    name: "Tanqueray London Dry",
    category: "Gin",
    price: 4200,
    size: "750ml",
    rating: 4.8,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0036-HDG",
    name: "Hendrick's Gin",
    category: "Gin",
    price: 5800,
    size: "750ml",
    rating: 4.9,
    badge: "Premium",
    emoji: "🍸",
  },
  {
    id: "g7",
    name: "Roku Gin",
    category: "Gin",
    price: 4500,
    size: "700ml",
    rating: 4.8,
    emoji: "🍸",
  },
  {
    id: "wn1",
    name: "Four Cousins Sweet Red",
    category: "Wine",
    price: 1400,
    size: "750ml",
    rating: 4.6,
    badge: "Bestseller",
    emoji: "🍷",
  },
  {
    id: "wn2",
    name: "Drostdy Hof Adelpracht",
    category: "Wine",
    price: 1100,
    size: "750ml",
    rating: 4.4,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0066-NCB",
    name: "Nederburg Cabernet",
    category: "Wine",
    price: 1600,
    size: "750ml",
    rating: 4.7,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0068-4SSR",
    name: "4th Street Sweet Red",
    category: "Wine",
    price: 1300,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "wn5",
    name: "Robertson Winery Chardonnay",
    category: "Wine",
    price: 1500,
    size: "750ml",
    rating: 4.6,
    emoji: "🍷",
  },
  {
    id: "wn6",
    name: "Casillero del Diablo",
    category: "Wine",
    price: 2100,
    size: "750ml",
    rating: 4.7,
    emoji: "🍷",
  },
  {
    id: "wn7",
    name: "Namaqua Sweet Red",
    category: "Wine",
    price: 1400,
    size: "5L",
    rating: 4.4,
    badge: "Value",
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0039-JCQ",
    name: "Jose Cuervo Especial",
    category: "Tequila",
    price: 3400,
    size: "750ml",
    rating: 4.5,
    emoji: "🍹",
  },
  {
    id: "WH-IMG-0040-DJB",
    name: "Don Julio Blanco",
    category: "Tequila",
    price: 8500,
    size: "750ml",
    rating: 4.9,
    badge: "Premium",
    emoji: "🍹",
  },
  {
    id: "WH-IMG-0041-OLG",
    name: "Olmeca Gold",
    category: "Tequila",
    price: 2800,
    size: "750ml",
    rating: 4.4,
    emoji: "🍹",
  },
  {
    id: "t4",
    name: "Patrón Silver",
    category: "Tequila",
    price: 9200,
    size: "750ml",
    rating: 4.9,
    badge: "Luxury",
    emoji: "🍹",
  },
  {
    id: "t5",
    name: "Camino Real Gold",
    category: "Tequila",
    price: 2500,
    size: "750ml",
    rating: 4.3,
    emoji: "🍹",
  },
  {
    id: "WH-IMG-0044-HVS",
    name: "Hennessy VS Cognac",
    category: "Champagne",
    price: 5800,
    size: "700ml",
    rating: 4.8,
    badge: "Hot",
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0049-MCB",
    name: "Moët & Chandon Brut",
    category: "Champagne",
    price: 9500,
    size: "750ml",
    rating: 4.9,
    badge: "Luxury",
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0046-RMV",
    name: "Rémy Martin VSOP",
    category: "Champagne",
    price: 8200,
    size: "700ml",
    rating: 4.8,
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0050-VVC",
    name: "Veuve Clicquot Yellow",
    category: "Champagne",
    price: 11500,
    size: "750ml",
    rating: 4.9,
    emoji: "🍾",
  },
  {
    id: "c5",
    name: "Martell VS",
    category: "Champagne",
    price: 5200,
    size: "700ml",
    rating: 4.7,
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0051-DPG",
    name: "Dom Pérignon Vintage",
    category: "Champagne",
    price: 35000,
    size: "750ml",
    rating: 5,
    badge: "Luxury",
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0052-LBR",
    name: "Luc Belaire Rosé",
    category: "Champagne",
    price: 6800,
    size: "750ml",
    rating: 4.8,
    emoji: "🍾",
  },
  {
    id: "WH-IMG-0053-TSK",
    name: "Tusker Lager (Crate)",
    category: "Kenyan",
    price: 2400,
    size: "24x500ml",
    rating: 4.7,
    badge: "Local",
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0055-WCL",
    name: "White Cap Lager",
    category: "Kenyan",
    price: 2200,
    size: "24x500ml",
    rating: 4.5,
    badge: "Local",
    emoji: "🍺",
  },
  {
    id: "k3",
    name: "Balozi Premium",
    category: "Kenyan",
    price: 2100,
    size: "24x500ml",
    rating: 4.4,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0080-CHG",
    name: "Chrome Gin",
    category: "Kenyan",
    price: 950,
    size: "750ml",
    rating: 4.2,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0029-KBV",
    name: "Kibao Vodka",
    category: "Kenyan",
    price: 850,
    size: "750ml",
    rating: 4.1,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0079-KCC",
    name: "KC Cane Spirit",
    category: "Kenyan",
    price: 750,
    size: "750ml",
    rating: 4,
    emoji: "🍸",
  },
  {
    id: "k7",
    name: "Hunter's Gold Cider",
    category: "Kenyan",
    price: 280,
    size: "330ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0060-SVD",
    name: "Savanna Dry Cider",
    category: "Kenyan",
    price: 320,
    size: "330ml",
    rating: 4.6,
    emoji: "🍺",
  },
  {
    id: "k9",
    name: "Kenya Cane Smooth",
    category: "Kenyan",
    price: 750,
    size: "750ml",
    rating: 4.2,
    emoji: "🍸",
  },
  {
    id: "k10",
    name: "Chrome Lemon",
    category: "Kenyan",
    price: 950,
    size: "750ml",
    rating: 4.3,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0058-HNK",
    name: "Heineken Lager",
    category: "Beer",
    price: 2800,
    size: "24x330ml",
    rating: 4.7,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0095-GFE",
    name: "Guinness Foreign Extra",
    category: "Beer",
    price: 3200,
    size: "24x500ml",
    rating: 4.8,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0091-CRE",
    name: "Corona Extra",
    category: "Beer",
    price: 3400,
    size: "24x355ml",
    rating: 4.7,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0092-STA",
    name: "Stella Artois",
    category: "Beer",
    price: 3600,
    size: "24x330ml",
    rating: 4.7,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0059-BDW",
    name: "Budweiser",
    category: "Beer",
    price: 3000,
    size: "24x330ml",
    rating: 4.6,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0002-JWR",
    name: "Johnnie Walker Red Label",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0003-JWG",
    name: "Johnnie Walker Gold Label",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0010-GF15",
    name: "Glenfiddich 15",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0011-GL12",
    name: "Glenlivet 12",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0013-SNG15",
    name: "Singleton 15",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0016-MKS",
    name: "Monkey Shoulder",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0018-DWL",
    name: "Dewar’s White Label",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0019-THC",
    name: "Teacher’s Highland Cream",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0020-JBR",
    name: "J&B Rare",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0022-SMB",
    name: "Smirnoff Black",
    category: "Vodka",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0023-ABS",
    name: "Absolut Vodka",
    category: "Vodka",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0024-CIR",
    name: "Cîroc Snap Frost",
    category: "Vodka",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0025-BLV",
    name: "Belvedere Vodka",
    category: "Vodka",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0027-SKY",
    name: "Skyy Vodka",
    category: "Vodka",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0031-GDG",
    name: "Gordon’s Dry Gin",
    category: "Gin",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0034-BFG",
    name: "Beefeater Gin",
    category: "Gin",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0037-WHN",
    name: "Whitley Neill",
    category: "Gin",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0038-TN10",
    name: "Tanqueray No.10",
    category: "Gin",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0042-PTS",
    name: "Patron Silver",
    category: "Tequila",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍹",
  },
  {
    id: "WH-IMG-0043-1800R",
    name: "1800 Reposado",
    category: "Tequila",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍹",
  },
  {
    id: "WH-IMG-0045-HVSOP",
    name: "Hennessy VSOP",
    category: "Cognac",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0047-MBS",
    name: "Martell Blue Swift",
    category: "Cognac",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0048-CVS",
    name: "Courvoisier VS",
    category: "Cognac",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0054-TSM",
    name: "Tusker Malt",
    category: "Beer",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0056-BLZ",
    name: "Balozi Beer",
    category: "Beer",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0057-GNS",
    name: "Guinness Smooth",
    category: "Beer",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0061-HNT",
    name: "Hunters Choice",
    category: "Cider",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0062-FCR",
    name: "Four Cousins Red",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0063-FCW",
    name: "Four Cousins White",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0064-DHR",
    name: "Drostdy Hof Red",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0065-DHW",
    name: "Drostdy Hof White",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0067-RWSR",
    name: "Robertson Winery Sweet Red",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0069-4SSW",
    name: "4th Street Sweet White",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0070-BCB",
    name: "Bacardi Carta Blanca",
    category: "Rum",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0071-CMG",
    name: "Captain Morgan Gold",
    category: "Rum",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0072-MCR",
    name: "Malibu Coconut Rum",
    category: "Rum",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0073-CMDR",
    name: "Captain Morgan Dark Rum",
    category: "Rum",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0074-BLY",
    name: "Baileys Irish Cream",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0075-AMR",
    name: "Amarula",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0076-JGM",
    name: "Jägermeister",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0077-CMP",
    name: "Campari",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0078-MTR",
    name: "Martini Rosso",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0081-BSG",
    name: "Best Gin",
    category: "Kenyan",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🇰🇪",
  },
  {
    id: "WH-IMG-0082-KCCO",
    name: "Kenya Cane Coconut",
    category: "Kenyan",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🇰🇪",
  },
  {
    id: "WH-IMG-0083-BL1L",
    name: "Black Label 1L",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0084-JBB",
    name: "Jameson Black Barrel",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0085-JDH",
    name: "Jack Daniel’s Honey",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0086-JDF",
    name: "Jack Daniel’s Fire",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0087-GMO",
    name: "Glenmorangie Original",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0088-BMO",
    name: "Bushmills Original",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0089-JBW",
    name: "Jim Beam White",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0090-WT101",
    name: "Wild Turkey 101",
    category: "Whisky",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🥃",
  },
  {
    id: "WH-IMG-0093-DSP",
    name: "Desperados",
    category: "Beer",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0094-PLS",
    name: "Pilsner Lager",
    category: "Beer",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍺",
  },
  {
    id: "WH-IMG-0096-RPW",
    name: "Ricca Peach Wine",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0097-CCR",
    name: "Cellar Cask Red",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0098-THM",
    name: "Tall Horse Merlot",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0099-THC",
    name: "Tall Horse Chardonnay",
    category: "Wine",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍷",
  },
  {
    id: "WH-IMG-0100-PXC",
    name: "Patron XO Cafe",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0101-KHL",
    name: "Kahlúa",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0102-SCF",
    name: "Southern Comfort",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0103-DSR",
    name: "Disaronno",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0104-SMB",
    name: "Sambuca",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
  {
    id: "WH-IMG-0105-BLC",
    name: "Blue Curacao",
    category: "Liqueur",
    price: 3000,
    size: "750ml",
    rating: 4.5,
    emoji: "🍸",
  },
];

export const formatKES = (n: number) => "KES " + n.toLocaleString("en-KE");
